# Probability
## Introduction to Probabilities
In 1814, Pierre-Simon Laplace wrote:  
> Probability theory is nothing but common sense reduced to calculation. 
... [Probability] is thus simply a fraction whose numerator is the 
number of favorable cases and whose denominator is the number of all 
the cases possible ... when nothing leads us to expect that any one of 
these cases should occur more than any other.
Laplace nailed it. To untangle a probability problem, all you have to do 
is define exactly what the cases are, and careful count the favorable 
and total cases. Let's be clear on our vocabulary words:
- **Trial**
A single occurrence with an outcome that is uncertain until we observe it.  
*For example, rolling a single die.*
- **Outcome**
A possible result of a trial; one particular state of the world. What 
Laplace calls a **case.** *For example:* `4`.
- **Sample Space**
The set of all possible outcomes for the trial.   
*For example,* `{1, 2, 3, 4, 5, 6}`.
- **Event**
A subset of the sample space, a set of outcomes that together have some 
property we are interested in.  
*For example, the event "even die roll" is the set of outcomes* 
`{2, 4, 6}`.
- **Probability**
As Laplace said, the probability of an event with respect to a sample 
space is the "number of favorable cases" (outcomes from the sample space 
that are in the event) divided by the "number of all the cases" in the 
sample space (assuming "nothing leads us to expect that any one of these 
cases should occur more than any other"). Since this is a proper 
fraction, probability will always be a number between 0 (representing an 
impossible event) and 1 (representing a certain event).
*For example, the probability of an even die roll is 3/6 = 1/2.*

In [1]:
import random #generador de números aleatorios
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
#1.generación de lanzamiento de una moneda, sello = 0, cara = 1
toss = random.randint(0,1) 
print(toss)

1


In [11]:
# generación de lanzamiento de monedas, con una estructura de control (for) las secuencias de control son for, if, while.
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[0, 1, 0, 1, 0, 1, 0, 1, 1, 1]


In [15]:
# generación de lanzamiento de monedas controlado para ser reproducible. 
random.seed(2024)
toss_results = []
for i in range(10):
    result = random.randint(0,1)
    toss_results.append(result)
print(toss_results)

[1, 0, 1, 0, 1, 1, 0, 1, 1, 1]


In [31]:
# calcular la probabilidad de que salga cara en 10 lanzamientos de moneda
toss_results = []
for i in range(1000000):
    result = random.randint(0,1)
    toss_results.append(result)
#print(toss_results)
sum(toss_results)/len(toss_results)

0.498807

In [33]:
from fractions import Fraction

In [34]:
Fraction(1,3) #esta es la representación de una fracción en python 

Fraction(1, 3)

In [35]:
#2 calcular probabilidad de sacar par en un lanzamiento de dados
even = {2,4,6}
points = {1,2,3,4,5,6} #asumimos que el dado está perfectamente balanceado y que tiene 6 caras
set.intersection(even,points)


{2, 4, 6}

In [36]:
def Pr(event,space): 
    return Fraction(len(set.intersection(event,space)),len(space))

In [38]:
Pr(even,points) 

Fraction(1, 2)

In [39]:
# calcular la probabilidad de obtener 5 o 6 en un lanzamiento de dados
success = {5,6}
points = {1,2,3,4,5,6}
Pr(success,points) 

Fraction(1, 3)

This refers to a discrete sample space, so the probability is related to a discrete event

In [42]:
# box1 = [1,0,0,0]  la probabilidad de éxito es de 1/4= 0.25
# box2 = [1,1,0,0,0] la probabilidad de éxito es de 2/5= 0.4 
box1 = np.array([1,0,0,0]) #este es un vector ([]) 
np.random.choice(box1,1) #simula el evento de sacar una piedra ,1 es un evento

array([0])

In [44]:
trial = np.random.choice(box1,1000000)
trial.mean()

np.float64(0.250174)

In [45]:
box2 = np.array([1,0,1,0,0])
trial = np.random.choice(box2,100000)
trial.mean() #aquí funciona mean porque solo hay dos resultados 0 y 1 y además el resultado exitoso es 1. 


np.float64(0.40095)

In [47]:
#cuando son más de dos resultados se usa
success = np.isin(trial,[1])
probability = len(trial[success])/len(trial)
probability

0.40095

In [59]:
np.random.seed(2024)
yankenpo = np.array([1,2,3])
trial = np.random.choice(yankenpo,10)
success = np.isin(trial,[2]) #isin nos retorna un vector de booleanos 
probability = len(trial[success])/len(trial)
probability

0.2

In [53]:
yankenpo
trial
success

array([ True, False, False,  True, False, False, False, False, False,
        True])

In [54]:
trial

array([2, 3, 1, 2, 3, 3, 3, 3, 3, 2])

In [55]:
trial[success]

array([2, 2, 2])

In [60]:
results = np.array([14,22,21,15,18,23,19])
success = np.isin(results,[21])
results[success]

array([21])

In [77]:
#3 el siguiente problema muestra la probabilidad condicional 
#cuál es la probabilidad de sacar un As en una segunda extracción si en la primera extracción ya saqué un As
#cuántos Ases hay en una baraja: 4 
#cuántos naipes hay en una bajara: 52
#cuál es la probabilidad de sacar en la primera extracción un As: 4/52= 1/13
#si ya saqué un As de la baraja cuántos naipes quedan? 51 y 3 Ases
#en una segunda extracción cuál es la probabilidad de sacar un As? Pr(sacar As en segunda extracción|sacar As en la primera extracción)
#por lo tanto esto quiere decir que esta probabilidad está condicionada al evento se haber sacado un As en la primera extracción
#la fórmula para calcularlo sería Pr=3/51
#Pr(A and B)=Pr(A)*Pr(B|A)
#Si A y B son Independientes entonces Pr(A|B)=Pr(A)
#Pr(A and B and C)=Pr(A)*Pr(B|A)*Pr(C|A and B) *Regla de la cadena
#Pr(A or B)=Pr(A)+Pr(B)-Pr(A and B)
#en un avión hay 3 bombas, cada bomba tiene 0.4 probabilidades de explotar, entonces cuál es la probabilidad de que la segunda bomba explote?
#cuál es la probabilidad de que las 3 bombas exploten a la vez? 0.4*0.4*0.4
#cuál es la probabilidad de que en una sala con 10 personas dos cumplan años el mismo día. y en una sala con 20 personas? y en una sala con 30 personas? y en una sala con 50 personas? 
def same_birthday(n):
    days=np.arange(1,366)
    bday = np.random.choice(days,n)
    return np.any(np.bincount(bday)>1)
same_birthday(10)
counter = 0
for i in range(10000):
    if same_birthday(360):
        counter +=1
counter/10000


1.0